name: Rust Test and Publish

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup default stable

      - name: Build and Test
        run: |
          cargo build
          cargo test --verbose

      - name : Detect Tag
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: detect_tag
        with:
          create-tag: false
          version-command: cargo read-manifest | jq -r .version
      - uses: mathieudutour/github-tag-action@v5.6
        with:
          custom_tag: ${{ steps.detect_tag.outputs.current-version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.detect_tag.outputs.previous-version != steps.detect_tag.outputs.current-version }}

      - name: Hit Tag
        run: |
          git tag ${{ steps.detect_tag.outputs.current-version }}
          git push ${{ steps.detect_tag.outputs.current-version }}

      - name: Publish
        run: |
          cargo publish --token ${{ secrets.CRATES_TOKEN }}